name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        repository: firezone/firezone
    - name: Build the Docker image
      run: docker build . --file Dockerfile.prod --tag ghcr.io/telkomindonesia/firezone:$(date +%s)
